import type { BtcAutoTradingDashboard } from '@/types'

export type BtcAutoTradingExportLocale = 'zh' | 'en'

const csvCell = (value: string | number | boolean | null | undefined) => {
  const text = value === null || value === undefined ? '' : String(value)
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
}

const csvRow = (values: Array<string | number | boolean | null | undefined>) =>
  values.map(csvCell).join(',')

const labels = {
  zh: {
    metadata: '运行信息',
    summaries: '周期汇总',
    trades: '逐笔交易',
    generatedAt: '导出时间',
    strategyVersion: '策略版本',
    executionMode: '执行模式',
    lastSuccessAt: '最近成功周期',
    period: '周期',
    startAt: '开始时间',
    endAt: '结束时间',
    tradeCount: '交易数',
    wins: '盈利笔数',
    losses: '亏损笔数',
    winRatePct: '胜率%',
    grossProfit: '总盈利USDT',
    grossLoss: '总亏损USDT',
    netPnl: '净盈亏USDT',
    averageWinLossRatio: '平均盈亏比',
    profitFactor: 'Profit Factor',
    expectancyUsdt: '单笔期望USDT',
    maxDrawdownUsdt: '最大回撤USDT',
    id: '交易ID',
    symbol: '标的',
    direction: '方向',
    status: '状态',
    openedAt: '开仓时间',
    closedAt: '平仓时间',
    quantity: '数量',
    notionalUsdt: '名义仓位USDT',
    leverage: '杠杆',
    entryPrice: '入场价',
    exitPrice: '退出价',
    stopLoss: '止损价',
    takeProfit: '止盈价',
    grossPnl: '毛盈亏USDT',
    fees: '手续费USDT',
    fundingFee: '资金费USDT',
    returnPct: '收益率%',
    pnlSource: '盈亏口径',
    closeReason: '平仓原因',
    signalScore: '信号分',
    signalConfidence: '置信度%',
    error: '错误',
  },
  en: {
    metadata: 'Run metadata',
    summaries: 'Period summaries',
    trades: 'Trade ledger',
    generatedAt: 'Generated at',
    strategyVersion: 'Strategy version',
    executionMode: 'Execution mode',
    lastSuccessAt: 'Last successful cycle',
    period: 'Period',
    startAt: 'Start at',
    endAt: 'End at',
    tradeCount: 'Trades',
    wins: 'Wins',
    losses: 'Losses',
    winRatePct: 'Win rate %',
    grossProfit: 'Gross profit USDT',
    grossLoss: 'Gross loss USDT',
    netPnl: 'Net P&L USDT',
    averageWinLossRatio: 'Average win/loss ratio',
    profitFactor: 'Profit factor',
    expectancyUsdt: 'Expectancy USDT',
    maxDrawdownUsdt: 'Max drawdown USDT',
    id: 'Trade ID',
    symbol: 'Symbol',
    direction: 'Direction',
    status: 'Status',
    openedAt: 'Opened at',
    closedAt: 'Closed at',
    quantity: 'Quantity',
    notionalUsdt: 'Notional USDT',
    leverage: 'Leverage',
    entryPrice: 'Entry price',
    exitPrice: 'Exit price',
    stopLoss: 'Stop loss',
    takeProfit: 'Take profit',
    grossPnl: 'Gross P&L USDT',
    fees: 'Fees USDT',
    fundingFee: 'Funding fee USDT',
    returnPct: 'Return %',
    pnlSource: 'P&L source',
    closeReason: 'Close reason',
    signalScore: 'Signal score',
    signalConfidence: 'Confidence %',
    error: 'Error',
  },
} as const

export const buildBtcAutoTradingCsv = (
  dashboard: BtcAutoTradingDashboard,
  locale: BtcAutoTradingExportLocale,
  generatedAt = new Date(),
) => {
  const label = labels[locale]
  const rows = [
    csvRow([label.metadata]),
    csvRow([label.generatedAt, label.strategyVersion, label.executionMode, label.lastSuccessAt]),
    csvRow([
      generatedAt.toISOString(),
      dashboard.strategyVersion,
      dashboard.config.executionMode,
      dashboard.lastSuccessfulRunAt,
    ]),
    '',
    csvRow([label.summaries]),
    csvRow([
      label.period,
      label.startAt,
      label.endAt,
      label.tradeCount,
      label.wins,
      label.losses,
      label.winRatePct,
      label.grossProfit,
      label.grossLoss,
      label.netPnl,
      label.averageWinLossRatio,
      label.profitFactor,
      label.expectancyUsdt,
      label.maxDrawdownUsdt,
    ]),
    ...dashboard.performance.map((summary) =>
      csvRow([
        summary.period,
        summary.startAt,
        summary.endAt,
        summary.trades,
        summary.wins,
        summary.losses,
        summary.winRatePct,
        summary.grossProfit,
        summary.grossLoss,
        summary.netPnl,
        summary.averageWinLossRatio,
        summary.profitFactor,
        summary.expectancyUsdt,
        summary.maxDrawdownUsdt,
      ]),
    ),
    '',
    csvRow([label.trades]),
    csvRow([
      label.id,
      label.strategyVersion,
      label.executionMode,
      label.symbol,
      label.direction,
      label.status,
      label.openedAt,
      label.closedAt,
      label.quantity,
      label.notionalUsdt,
      label.leverage,
      label.entryPrice,
      label.exitPrice,
      label.stopLoss,
      label.takeProfit,
      label.grossPnl,
      label.fees,
      label.fundingFee,
      label.netPnl,
      label.returnPct,
      label.pnlSource,
      label.closeReason,
      label.signalScore,
      label.signalConfidence,
      label.error,
    ]),
    ...dashboard.trades.map((trade) =>
      csvRow([
        trade.id,
        trade.strategyVersion,
        trade.executionMode,
        trade.symbol,
        trade.direction,
        trade.status,
        trade.openedAt,
        trade.closedAt,
        trade.quantity,
        trade.notionalUsdt,
        trade.leverage,
        trade.entryPrice,
        trade.exitPrice,
        trade.stopLoss,
        trade.takeProfit,
        trade.grossPnl,
        trade.fees,
        trade.fundingFee,
        trade.netPnl,
        trade.returnPct,
        trade.pnlSource,
        trade.closeReason,
        trade.signalScore,
        trade.signalConfidence,
        trade.error,
      ]),
    ),
  ]
  return `\uFEFF${rows.join('\r\n')}\r\n`
}
