/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.kols.jsonc --include-runtime=false --strict-vars=false --env-interface=KolsEnv worker/kols-env.d.ts` (hash: f705f19820945b232cd13c4c5475a8f2)
interface __BaseEnv_KolsEnv {
	DB: D1Database;
	ALLOWED_ORIGINS: string;
	RSSHUB_FETCHER: Fetcher /* web3-rsshub */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./kols");
	}
	interface Env extends __BaseEnv_KolsEnv {}
}
interface KolsEnv extends __BaseEnv_KolsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
